//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temperatura
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int temperatura1 { get; set; }
        public int cidade_id { get; set; }
    
        public virtual Cidade Cidade { get; set; }
    }
}
